### PR TITLE
Updated the Project.md file

### PR DESCRIPTION
**Pull request by ymaheshwari1**

### CODE REVIEW

**Comment by ymaheshwari1** [comment]
@Ajitesh13 Please check this

**Comment by Ajitesh13** [comment]
Looks good to me

**Comment by Ajitesh13** [comment]
Just make the checks passed, So that I can merge this PR

**Comment by ymaheshwari1** [comment]
@Ajitesh13 I am not able to pass this check. Can you guide me for this?

**Comment by Ajitesh13** [comment]
@ymaheshwari1 Follow the istructions here: https://github.com/HakinCodes/extension-activity-logger/pull/14#issue-473625877 IF you still need help, feel free to ask

**Comment by ymaheshwari1** [comment]
@Ajitesh13 I have done the changes.

**Comment by Ajitesh13** [comment]
Thanks for the PR!

**Pull request merged**
